version: '3'

volumes:
  flash_local_postgres_data: {}
  flash_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: flash_local_django
    container_name: flash_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15.1
    container_name: flash_local_postgres
    volumes:
      - flash_local_postgres_data:/var/lib/postgresql/data
      - flash_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: flash_local_docs
    container_name: flash_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./flash:/app/flash:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: flash_local_redis

  celeryworker:
    <<: *django
    image: flash_local_celeryworker
    container_name: flash_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: flash_local_celerybeat
    container_name: flash_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: flash_local_flower
    container_name: flash_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
