---

volumes:
  production_postgres_data: {}
  production_django_media: {}
  production_django_static: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: flash_production_django
    volumes:
      - production_django_media:/app/flash/media
      - production_django_static:/app/staticfiles
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: flash_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: flash_production_celeryworker
    command: /start-celeryworker
    volumes:
      - ./cookies_46.txt:/app/cookies_46.txt
      - ./cookies_127.txt:/app/cookies_127.txt
      - ./cookies_148.txt:/app/cookies_148.txt

  celerybeat:
    <<: *django
    image: flash_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: flash_production_flower
    command: /start-flower

  readability:
    container_name: flash_local_readability
    build:
      context: ./compose/local/readability
    image: flash_local_readability
    ports:
      - '8081:8081'

  flash:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: flash_production_flash
    depends_on:
      - django
    ports:
      - 8100:80
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
      - production_django_static:/usr/share/nginx/static:ro

  mkfd:
    container_name: flash_local_mkfd
    image: tbosk/mkfd:23
    ports:
      - 5000:5000
    environment:
      - PASSKEY=your_passkey
      - COOKIE_SECRET=your_cookie_secret
      - ENCRYPTION_KEY=your__encryption
    volumes:
      - ./mkfd:/configs:z
