---

volumes:
  production_django_media: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: flash_production_django
    volumes:
      - production_django_media:/app/flash/media
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: flash_production_celeryworker
    command: /start-celeryworker
    volumes:
      - ./cookies_46.txt:/app/cookies_46.txt
      - ./cookies_127.txt:/app/cookies_127.txt
      - ./cookies_148.txt:/app/cookies_148.txt

  celerybeat:
    <<: *django
    image: flash_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: flash_production_flower
    command: /start-flower

  readability:
    container_name: flash_local_readability
    build:
      context: ./compose/local/readability
    image: flash_local_readability
    ports:
      - '8081:8081'

  flash:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: flash_production_flash
    depends_on:
      - django
    ports:
      - 8100:80
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
