---

volumes:
  flash_local_postgres_data: {}
  flash_local_redis_data: {}
  flash_local_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: flash_local_django
    container_name: flash_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - ./.cache/pre-commit:/root/.cache/pre-commit:z
      - ./.cache/huggingface:/root/.cache/huggingface:z
      - flash_local_django_media:/app/flash/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  redis:
    image: docker.io/redis:6
    container_name: flash_local_redis
    volumes:
      - flash_local_redis_data:/data

  celeryworker:
    <<: *django
    image: flash_local_celeryworker
    container_name: flash_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: flash_local_celerybeat
    container_name: flash_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: flash_local_flower
    container_name: flash_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  frontend:
    container_name: flash_local_frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: frontend-builder
    image: flash_local_frontend
    command: yarn dev --port 80 --host 0
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src

  readability:
    container_name: flash_local_readability
    build:
      context: ./compose/local/readability
    image: flash_local_readability
    ports:
      - '8081:8081'

  flash:
    image: nginx:1.27.3-bookworm
    ports:
      - 8100:80
    depends_on:
      - django
      - frontend
    volumes:
      - ./compose/local/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: pgvector/pgvector:pg15
    container_name: flash_local_postgres
    restart: unless-stopped
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - flash_local_postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: flash_local_adminer
    restart: always
    ports:
      - 8090:8080
    links:
      - postgres
    depends_on:
      - postgres

  mkfd:
    container_name: flash_local_mkfd
    image: tbosk/mkfd:23
    ports:
      - 5000:5000
    environment:
      - PASSKEY=your_passkey
      - COOKIE_SECRET=your_cookie_secret
      - ENCRYPTION_KEY=your__encryption
    volumes:
      - ./mkfd:/configs:z
