# Generated by Django 5.0.10 on 2025-01-20 20:16

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.TextField(blank=True, null=True)),
                ('title_original', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content_original', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('homepage', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('language', models.TextField()),
                ('title', models.TextField()),
                ('license', models.TextField(blank=True, null=True)),
                ('icon', models.TextField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('incomplete', models.BooleanField(blank=True, null=True)),
                ('salt_url', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('premium', models.BooleanField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('exclude', models.TextField(blank=True, null=True)),
                ('main', models.TextField(blank=True, null=True)),
                ('tor', models.BooleanField(blank=True, null=True)),
                ('asy', models.BooleanField(blank=True, null=True)),
                ('iconblob', models.BinaryField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'feeds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticlesData',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='news.articles')),
                ('feed_id', models.IntegerField(blank=True, null=True)),
                ('epoch', models.FloatField(blank=True, null=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('to_reads', models.BigIntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles_data',
                'managed': False,
            },
        ),
    ]
