# Generated by Django 5.0.10 on 2025-01-20 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.BooleanField(default=False)),
                ('list_email', models.TextField(blank=True)),
                ('list_frequency', models.TextField(default='daily')),
                ('list_news', models.IntegerField(default=10)),
                ('list_format', models.TextField(default='pdf')),
                ('whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('whitelist_authors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('blacklist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('blacklist_authors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('sociality_weight', models.IntegerField(default=0)),
                ('gravity', models.FloatField(default=2.0)),
                ('age_divider', models.FloatField(default=100.0)),
                ('feed_weight', models.IntegerField(default=0)),
                ('list_weight', models.IntegerField(default=0)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('bow', models.JSONField(default=dict)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('list_hour', models.IntegerField(default=7)),
                ('list_fulltext', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
