# Generated by Django 5.0.10 on 2025-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCombined',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stamp', models.DateTimeField()),
                ('author', models.TextField(blank=True, null=True)),
                ('title_original', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content_original', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
                ('feed_id', models.IntegerField()),
                ('views', models.BigIntegerField()),
                ('rating', models.FloatField()),
                ('to_reads', models.FloatField()),
                ('length', models.IntegerField()),
                ('excerpt', models.TextField(null=True)),
            ],
            options={
                'db_table': 'articles_combined',
                'managed': False,
            },
        ),
    ]
