# Generated by Django 5.0.10 on 2025-02-20 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articlescombined'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedsCombined',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('homepage', models.TextField()),
                ('url', models.TextField()),
                ('language', models.TextField()),
                ('title', models.TextField()),
                ('license', models.TextField(blank=True, null=True)),
                ('icon', models.TextField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('incomplete', models.BooleanField(blank=True, null=True)),
                ('salt_url', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('premium', models.BooleanField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('exclude', models.TextField(blank=True, null=True)),
                ('main', models.TextField(blank=True, null=True)),
                ('tor', models.BooleanField(blank=True, null=True)),
                ('asy', models.BooleanField(blank=True, null=True)),
                ('iconblob', models.BinaryField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('last_polled_epoch', models.FloatField(blank=True, null=True)),
                ('article_count', models.BigIntegerField(blank=True, null=True)),
                ('average_time_from_last_post', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feeds_combined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedsData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_polled_epoch', models.FloatField(blank=True, null=True)),
                ('article_count', models.BigIntegerField(blank=True, null=True)),
                ('average_time_from_last_post', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feeds_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='feeds',
            options={'managed': False, 'verbose_name': 'feed', 'verbose_name_plural': 'feeds'},
        ),
    ]
