# Generated by Django 5.1.8 on 2025-05-03 17:04

import django.db.models.deletion
from django.db import migrations, models


def create_views(apps, schema_editor):

    delete_views(apps, schema_editor)

    with schema_editor.connection.cursor() as cursor:

        cursor.execute("""
                       CREATE VIEW feeds_combined AS (
                            SELECT
                                feeds.*,
                                COALESCE(news_feedicons.image, '/static/icons/unknown.png') AS image,
                                feeds_data.last_polled_epoch,
                                feeds_data.article_count,
                                feeds_data.average_time_from_last_post
                            FROM
                                feeds
                                LEFT OUTER JOIN news_feedicons ON feeds.id = news_feedicons.feed_id
                                LEFT OUTER JOIN feeds_data ON feeds.id = feeds_data.id)""")

def delete_views(apps, schema_editor):

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS feeds_combined")


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_guestarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedIcons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='icons/')),
                ('stamp', models.DateTimeField(auto_now=True)),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.feeds')),
            ],
        ),
        migrations.RunPython(create_views, reverse_code=delete_views),
    ]
