# Generated by Django 5.1.8 on 2025-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20250514_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_bot_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mastodon_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mastodon_api_base_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mastodon_client_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mastodon_client_secret',
            field=models.TextField(blank=True),
        ),
    ]
