# Generated by Django 5.1.8 on 2025-05-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_mastodon_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_start_time', models.DateTimeField()),
                ('poll_end_time', models.DateTimeField()),
                ('http_status_code', models.IntegerField()),
                ('articles_retrieved', models.IntegerField()),
                ('articles_failed', models.IntegerField()),
                ('articles_stored', models.IntegerField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stats', to='news.feeds')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
