# Generated by Django 5.1.8 on 2025-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_feedpolling'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mastodon_list_name',
            field=models.TextField(blank=True, default='newsfeed', help_text='The name of the UserArticleList to publish to Mastodon.'),
        ),
        migrations.AddField(
            model_name='userarticles',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
