# Generated by Django 6.0.6 on 2026-07-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_profile_mastodon_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpolling',
            name='articles_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
